-- MySQL Script generated by MySQL Workbench
-- mar 23 ago 2016 22:12:39 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema colecciones
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colecciones
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colecciones` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `colecciones` ;

-- -----------------------------------------------------
-- Table `colecciones`.`tipoColeccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colecciones`.`tipoColeccion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colecciones`.`coleccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colecciones`.`coleccion` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `tipoColeccion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_coleccion_tipoColeccion1_idx` (`tipoColeccion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_coleccion_tipoColeccion1`
    FOREIGN KEY (`tipoColeccion_id`)
    REFERENCES `colecciones`.`tipoColeccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `colecciones`.`elemento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `colecciones`.`elemento` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `num` VARCHAR(45) NULL COMMENT '',
  `nombre` VARCHAR(45) NULL COMMENT '',
  `existe` TINYINT(1) NULL COMMENT '',
  `coleccion_id` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '',
  INDEX `fk_elemento_coleccion_idx` (`coleccion_id` ASC)  COMMENT '',
  CONSTRAINT `fk_elemento_coleccion`
    FOREIGN KEY (`coleccion_id`)
    REFERENCES `colecciones`.`coleccion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
